const UPCOMING_EVENTS_COUNT = 10;
const CONCLUDED_EVENTS_COUNT = 3;
const LATEST_ARTICLES_COUNT = 5;

module.exports = {
    UPCOMING_EVENTS_COUNT,
    CONCLUDED_EVENTS_COUNT,
    LATEST_ARTICLES_COUNT
};